### PR TITLE
Updated README.md

### LINKED ISSUE #3: Need a README File
Require a clean README.md file

### PR DESCRIPTION
**Pull request by AvineshTripathi**
some changes for readme which fixes #3

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Amazing work

**Comment by Rasesh2005** [comment]
You have done an excellent contribution… you are good at making Markdown files

**Comment by AvineshTripathi** [comment]
I have merged this still cant find this to be done in my hacktoberfest profile can you help me with it

**Comment by Rasesh2005** [comment]
May be this helps, check a tell me

**Pull request merged**
